[release]
schemaVersion = 1
releaseType = "minor"
bomVersion = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"

[modules.slb4j]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-ext]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-ext-layouts]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-ext-swing]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-ext-fx]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-config]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-config-json]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-config-yaml]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-config-xml]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"

[modules.slb4j-config-all]
version = "0.13.0"
sourceRevision = "2bb3081ead795aa551465969a19be3c85236f7c4"
selected = true
reason = "minor release"
