[release]
schemaVersion = 2
bomVersion = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"

[modules.slb4j]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["src"]

[modules.slb4j-ext]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-ext/src", "slb4j-ext/build.gradle.kts"]

[modules.slb4j-ext-layouts]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-ext/slb4j-ext-layouts/src", "slb4j-ext/slb4j-ext-layouts/build.gradle.kts"]

[modules.slb4j-ext-swing]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-ext/slb4j-ext-swing/src", "slb4j-ext/slb4j-ext-swing/build.gradle.kts"]

[modules.slb4j-ext-fx]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-ext/slb4j-ext-fx/src", "slb4j-ext/slb4j-ext-fx/build.gradle.kts"]

[modules.slb4j-config]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-config/src", "slb4j-config/build.gradle.kts"]

[modules.slb4j-config-json]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-config/slb4j-config-json/src", "slb4j-config/slb4j-config-json/build.gradle.kts"]

[modules.slb4j-config-yaml]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-config/slb4j-config-yaml/src", "slb4j-config/slb4j-config-yaml/build.gradle.kts"]

[modules.slb4j-config-xml]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-config/slb4j-config-xml/src", "slb4j-config/slb4j-config-xml/build.gradle.kts"]

[modules.slb4j-config-all]
version = "0.12.5"
publishedRevision = "a023d6f5e9a57079c0429fbec2dfa45a05936ce2"
paths = ["slb4j-config/slb4j-config-all/src", "slb4j-config/slb4j-config-all/build.gradle.kts"]
